### ISSUE TITLE
List prices (Tick)

### ISSUE THREAD

**Issue by brunocassol** [eeonevision/kucoin-go#1]
First! Thanks for writing and publishing it!

I couldn't find a method to fetch all market prices as defined here: https://kucoinapidocs.docs.apiary.io/#reference/0/market/tick(open)

Perhaps I'm missing something but if not, would you be interested in a contribution for this?

**Comment by brunocassol** [comment]
Nevermind. Found it!

The lib does this using .GetSymbols() which calls https://api.kucoin.com/v1/market/open/symbols

Closing the issue.

**Comment by eeonevision** [comment]
Thanks for using!
Fell free to ask and contribute for this project 👍
