### ISSUE TITLE
POST methods CreateOrder and CreateWithdrawlApply fail

### ISSUE THREAD

**Issue by kb1900** [eeonevision/kucoin-go#2]
Hi there @eeonevision - thank you for creating this wrapper. Though most things are working, I am having trouble to get any of the POST methods to work (CreateWithdrawalApply and CreateOrder). The only returns I am able to get are 

- CreateWithdrawlApply yielding: `{"code":"UNAUTH","msg":"This API Key was disabled","success":false,"timestamp":1525266653479}`
which does not make sense as it occurs with new api keys and other functions are working fine

- `kucoin_client.CreateOrder(coin_pair, "SELL", price, amount)` yielding: `{"code":"UNAUTH","msg":"Signature verification failed","success":false,"timestamp":1525266732191}`

Is there an updated version that you have or do you have any insight into these responses

**Comment by eeonevision** [comment]
Hi!
Kucoin API has been change *create order* endpoint, so it was not worked.
I already fixed this. Check :)
Also added new enpoint OrderBooks.

About CreateWithdrawApply don't know, may be you prefer need to write to support of kucoin?
Your keys are not permitted for withdraw.

**Comment by kb1900** [comment]
you are amazing. thank you so much for the fixes

**Comment by eeonevision** [comment]
Found issue in CreateWithdrawalApply method. 
Fix it bit later (in one day) and release with CancelOrder feature together )

edit. No, issue not on wrapper side.
